import { chromium, devices } from "@playwright/test";
const b = await chromium.launch();
const c = await b.newContext({ ...devices["iPhone 15"], locale: "zh-CN" });
const p = await c.newPage();
p.on("console", (m) => { if (m.type() === "error") console.log("CONSOLE ERROR:", m.text().slice(0, 200)); });
p.on("pageerror", (e) => console.log("PAGE ERROR:", String(e).slice(0, 300)));
await p.goto("http://127.0.0.1:5199/#/", { waitUntil: "networkidle" });
await p.waitForTimeout(500);
await p.getByTestId("start-training").click();
await p.waitForTimeout(1500);
console.log("URL:", p.url());
const overflow = await p.evaluate(() => ({ widest: Math.max(document.documentElement.scrollWidth, document.body.scrollWidth), vw: window.innerWidth }));
console.log("overflow:", JSON.stringify(overflow));
await p.screenshot({ path: "test-results/shots/live-start.png" });
const btn = await p.getByRole("button", { name: /完成本组/ }).first();
await btn.click();
await p.waitForTimeout(1200);
await p.screenshot({ path: "test-results/shots/live-rest.png" });
console.log("after set:", (await p.locator("body").innerText()).replace(/\n+/g, " | ").slice(0, 400));
await b.close();
